global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#alerts'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"
